# Generated by Django 3.0.1 on 2020-01-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20200101_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='param',
            new_name='paradigm',
        ),
    ]
