# Generated by Django 3.0.1 on 2020-01-01 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_progamer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progamer',
            new_name='Progammer',
        ),
    ]
